// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFsH8p9P5guivNTj90PmFIm5nLeQDgSjo',
    appId: '1:419781318218:web:1f8af0f90605bfdd8378b3',
    messagingSenderId: '419781318218',
    projectId: 'eshop-be005',
    authDomain: 'eshop-be005.firebaseapp.com',
    storageBucket: 'eshop-be005.firebasestorage.app',
    measurementId: 'G-YT3H53YQPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCWksAHQ9w3HtoURF9_LKafKXjl8f5Ss',
    appId: '1:419781318218:android:fc63b705e3f146a58378b3',
    messagingSenderId: '419781318218',
    projectId: 'eshop-be005',
    storageBucket: 'eshop-be005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7R2X2bzyzoGuEtMrfJbDyPRY3utBdgi4',
    appId: '1:419781318218:ios:ac212b4f0b57afbc8378b3',
    messagingSenderId: '419781318218',
    projectId: 'eshop-be005',
    storageBucket: 'eshop-be005.firebasestorage.app',
    androidClientId: '419781318218-7dvsbphlg2uct1n8fltuarcv83skrirk.apps.googleusercontent.com',
    iosClientId: '419781318218-e66i5r7v6a2lslhsca9cu8lbem9ktddc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7R2X2bzyzoGuEtMrfJbDyPRY3utBdgi4',
    appId: '1:419781318218:ios:ac212b4f0b57afbc8378b3',
    messagingSenderId: '419781318218',
    projectId: 'eshop-be005',
    storageBucket: 'eshop-be005.firebasestorage.app',
    androidClientId: '419781318218-7dvsbphlg2uct1n8fltuarcv83skrirk.apps.googleusercontent.com',
    iosClientId: '419781318218-e66i5r7v6a2lslhsca9cu8lbem9ktddc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFsH8p9P5guivNTj90PmFIm5nLeQDgSjo',
    appId: '1:419781318218:web:cdeb7c597830fba38378b3',
    messagingSenderId: '419781318218',
    projectId: 'eshop-be005',
    authDomain: 'eshop-be005.firebaseapp.com',
    storageBucket: 'eshop-be005.firebasestorage.app',
    measurementId: 'G-8X9D7MF0PW',
  );

}
